services:
  mailhog:
    image: axllent/mailpit:v1.28
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:mail.my127.site
      - traefik.port=8025
    environment:
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - private
      - shared
networks:
  private:
    external: false
  shared:
    external:
      name: $TRAEFIK_NETWORK
