services:
  kibana:
    build:
      context: kibana
    depends_on:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.http.routers.kibana.rule=Host(`kibana.my127.site`)
      - traefik.http.services.kibana.loadbalancer.server.port=5601
      - traefik.docker.network=${TRAEFIK_NETWORK}
    networks:
      - shared
      - private

  elasticsearch:
    build:
      context: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - private

  filebeat:
    build:
      context: filebeat
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - filebeat_data:/usr/share/filebeat/data:rw
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private

  metricbeat:
    build:
      context: metricbeat
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    command: ["-system.hostfs=/hostfs"]
    networks:
      - private
      - shared

volumes:
  filebeat_data: ~

networks:
  private:
    external: false
  shared:
    external:
      name: $TRAEFIK_NETWORK
