version: '3'
services:
  traefik:
    container_name: my127ws-proxy
    build: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.frontend.rule=Host:my127.site
      - traefik.port=8080
      - co.elastic.logs/module=traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config/my127ws/proxy:/config
      - ./traefik/root/tls:/tls
    networks:
      - private
      - shared
      - monitoring
    command: ['--docker']
networks:
  private:
    external: false
  shared:
    external:
      name: $TRAEFIK_NETWORK
  monitoring:
    external:
      name: ${TRAEFIK_NETWORK}_monitoring
