services:
  traefik:
    container_name: my127ws-proxy
    build: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=${TRAEFIK_PROXY_RULE}
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - co.elastic.logs/module=traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/root/tls:/tls
    networks:
      - private
      - shared
networks:
  private:
    external: false
  shared:
    external:
      name: $TRAEFIK_NETWORK
