
command('global service logger (enable|disable)', 'global service logger'):
  env:
    MY127WS_PROXY_DOMAIN: = @('global.service.proxy.domain')
  exec: |
    #!bash|=
    ws-service logger ={input.command(4)}

command('global service mail (enable|disable)', 'global service mail'):
  description: Actions for mailhog
  env:
    MY127WS_PROXY_DOMAIN: = @('global.service.proxy.domain')
  exec: |
    #!bash|=
    ws-service mail ={input.command(4)}

command('global service proxy (enable|disable|restart)', 'global service proxy'):
  description: Actions for Traefik proxy
  exec: |
    #!bash|=
    ws-service proxy ={input.command(4)}

command('global service tracing (start|stop|restart)', 'global service tracing'):
  env:
    MY127WS_PROXY_DOMAIN: = @('global.service.proxy.domain')
  exec: |
    #!bash|=
    ws-service tracing ={input.command(4)}

command('global service', 'global service'):
  description: Perform an action (start/stop etc.) on a global service
  exec: |
    #!bash|=
    ws-service

command('global config get <key>', 'global config get'):
  description: Retrieve a given workspace configuration by key
  exec: |
    #!bash|=
    echo "={@(input.argument('key'))}"

command('poweroff', 'poweroff'):
  description: Completely disable workspace by shutting down all containers
  exec: |
    #!bash(cwd:/)
    ws-poweroff
