version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:1
    restart: unless-stopped
    labels:
      - traefik.backend=jaeger
      - traefik.frontend.rule=Host:tracing.my127.site
      - traefik.docker.network=my127ws
      - traefik.port=16686

networks:
  default:
    external:
      name: $TRAEFIK_NETWORK
