on:
  release:
    types:
      - created

name: Attach PHAR to release

jobs:
  build:
    name: Compile and upload Phar
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      -
        name: "Composer install"
        uses: "ramsey/composer-install@v1"

      - name: Build PHAR
        run: composer compile ${{ github.event.release.tag_name }}

      - name: Check existence of compiled .phar
        run: test -e my127ws.phar && exit 0 || exit 10

      - name: Rename PHAR
        run: mv my127ws.phar ws
      
      - name: Generate sha256sum
        run: sha256sum ws > ws.sha256sum

      - name: "Upload PHAR to Release"
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ws
            ws.sha256sum
